export const MTR_LINES = {
  AEL: {
    zh: "機場快綫",
    en: "Airport Express Line",
    color: "#00888A",
    up_terminus: "機場及博覽館",
    down_terminus: "香港",
    stations: {
      AWE: { zh: "博覽館", en: "AsiaWorld Expo" },
      AIR: { zh: "機場", en: "Airport" },
      TSY: { zh: "青衣", en: "Tsing Yi" },
      KOW: { zh: "九龍", en: "Kowloon" },
      HOK: { zh: "香港", en: "Hong Kong" },
    },
  },
  TCL: {
    zh: "東涌綫",
    en: "Tung Chung Line",
    color: "#F7943E",
    up_terminus: "東涌",
    down_terminus: "香港",
    stations: {
      TUC: { zh: "東涌", en: "Tung Chung" },
      SUN: { zh: "欣澳", en: "Sunny Bay" },
      TSY: { zh: "青衣", en: "Tsing Yi" },
      LAK: { zh: "荔景", en: "Lai King" },
      NAC: { zh: "南昌", en: "Nam Cheong" },
      OLY: { zh: "奧運", en: "Olympic" },
      KOW: { zh: "九龍", en: "Kowloon" },
      HOK: { zh: "香港", en: "Hong Kong" },
    },
  },
  TKL: {
    zh: "將軍澳綫",
    en: "Tseung Kwan O Line",
    color: "#8D45AB",
    up_terminus: "寶琳及康城",
    down_terminus: "北角",
    stations: {
      POA: { zh: "寶琳", en: "Po Lam" },
      HAH: { zh: "坑口", en: "Hang Hau" },
      LHP: { zh: "康城", en: "LOHAS Park" },
      TKO: { zh: "將軍澳", en: "Tseung Kwan O" },
      TIK: { zh: "調景嶺", en: "Tiu Keng Leng" },
      YAT: { zh: "油塘", en: "Yau Tong" },
      QUB: { zh: "鰂魚涌", en: "Quarry Bay" },
      NOP: { zh: "北角", en: "North Point" },
    },
  },
  TML: {
    zh: "屯馬綫",
    en: "Tuen Ma Line",
    color: "#9C2E00",
    up_terminus: "屯門",
    down_terminus: "烏溪沙",
    stations: {
      TUM: { zh: "屯門", en: "Tuen Mun" },
      SIH: { zh: "兆康", en: "Siu Hong" },
      TIS: { zh: "天水圍", en: "Tin Shui Wai" },
      LOP: { zh: "朗屏", en: "Long Ping" },
      YUL: { zh: "元朗", en: "Yuen Long" },
      KSR: { zh: "錦上路", en: "Kam Sheung Road" },
      TWW: { zh: "荃灣西", en: "Tsuen Wan West" },
      MEF: { zh: "美孚", en: "Mei Foo" },
      NAC: { zh: "南昌", en: "Nam Cheong" },
      AUS: { zh: "柯士甸", en: "Austin" },
      ETS: { zh: "尖東", en: "East Tsim Sha Tsui" },
      HUH: { zh: "紅磡", en: "Hung Hom" },
      HOM: { zh: "何文田", en: "Ho Man Tin" },
      TKW: { zh: "土瓜灣", en: "To Kwa Wan" },
      SUW: { zh: "宋皇臺", en: "Sung Wong Toi" },
      KAT: { zh: "啟德", en: "Kai Tak" },
      DIH: { zh: "鑽石山", en: "Diamond Hill" },
      HIK: { zh: "顯徑", en: "Hin Keng" },
      TAW: { zh: "大圍", en: "Tai Wai" },
      CKT: { zh: "車公廟", en: "Che Kung Temple" },
      STW: { zh: "沙田圍", en: "Sha Tin Wai" },
      CIO: { zh: "第一城", en: "City One" },
      SHM: { zh: "石門", en: "Shek Mun" },
      TSH: { zh: "大水坑", en: "Tai Shui Hang" },
      HEO: { zh: "恆安", en: "Heng On" },
      MOS: { zh: "馬鞍山", en: "Ma On Shan" },
      WKS: { zh: "烏溪沙", en: "Wu Kai Sha" },
    },
  },
  EAL: {
    zh: "東鐵綫",
    en: "East Rail Line",
    color: "#5EB6E4",
    up_terminus: "羅湖及落馬洲",
    down_terminus: "金鐘",
    stations: {
      LMC: { zh: "落馬洲", en: "Lok Ma Chau" },
      LOW: { zh: "羅湖", en: "Lo Wu" },
      SHS: { zh: "上水", en: "Sheung Shui" },
      FAN: { zh: "粉嶺", en: "Fanling" },
      TWO: { zh: "太和", en: "Tai Wo" },
      TAP: { zh: "大埔墟", en: "Tai Po Market" },
      UNI: { zh: "大學", en: "University" },
      RAC: { zh: "馬場", en: "Racecourse" },
      FOT: { zh: "火炭", en: "Fo Tan" },
      SHT: { zh: "沙田", en: "Sha Tin" },
      TAW: { zh: "大圍", en: "Tai Wai" },
      KOT: { zh: "九龍塘", en: "Kowloon Tong" },
      MKK: { zh: "旺角東", en: "Mong Kok East" },
      HUH: { zh: "紅磡", en: "Hung Hom" },
      EXC: { zh: "會展", en: "Exhibition Centre" },
      ADM: { zh: "金鐘", en: "Admiralty" },
    },
  },
  SIL: {
    zh: "南港島綫",
    en: "South Island Line",
    color: "#C8AA4D",
    up_terminus: "海怡半島",
    down_terminus: "金鐘",
    stations: {
      SOH: { zh: "海怡半島", en: "South Horizons" },
      LET: { zh: "利東", en: "Lei Tung" },
      WCH: { zh: "黃竹坑", en: "Wong Chuk Hang" },
      OCP: { zh: "海洋公園", en: "Ocean Park" },
      ADM: { zh: "金鐘", en: "Admiralty" },
    },
  },
  TWL: {
    zh: "荃灣綫",
    en: "Tsuen Wan Line",
    color: "#E60012",
    up_terminus: "荃灣",
    down_terminus: "中環",
    stations: {
      TSW: { zh: "荃灣", en: "Tsuen Wan" },
      TWH: { zh: "大窩口", en: "Tai Wo Hau" },
      KWH: { zh: "葵興", en: "Kwai Hing" },
      KWF: { zh: "葵芳", en: "Kwai Fong" },
      LAK: { zh: "茘景", en: "Lai King" },
      MEF: { zh: "美孚", en: "Mei Foo" },
      LCK: { zh: "茘枝角", en: "Lai Chi Kok" },
      CSW: { zh: "長沙灣", en: "Cheung Sha Wan" },
      SSP: { zh: "深水埗", en: "Sham Shui Po" },
      PRE: { zh: "太子", en: "Prince Edward" },
      MOK: { zh: "旺角", en: "Mong Kok" },
      YMT: { zh: "油麻地", en: "Yau Ma Tei" },
      JOR: { zh: "佐敦", en: "Jordan" },
      TST: { zh: "尖沙咀", en: "Tsim Sha Tsui" },
      ADM: { zh: "金鐘", en: "Admiralty" },
      CEN: { zh: "中環", en: "Central" },
    },
  },
  ISL: {
    zh: "港島線",
    en: "Island Line",
    color: "#0075C2",
    up_terminus: "柴灣",
    down_terminus: "堅尼地城",
    stations: {
      CHW: { zh: "柴灣", en: "Chai Wan" },
      HFC: { zh: "杏花邨", en: "Heng Fa Chuen" },
      SKW: { zh: "筲箕灣", en: "Shau Kei Wan" },
      SWH: { zh: "西灣河", en: "Sai Wan Ho" },
      TAK: { zh: "太古", en: "Tai Koo" },
      QUB: { zh: "鰂魚涌", en: "Quarry Bay" },
      NOP: { zh: "北角", en: "North Point" },
      FOH: { zh: "炮台山", en: "Fortress Hill" },
      TIH: { zh: "天后", en: "Tin Hau" },
      CAB: { zh: "銅鑼灣", en: "Causeway Bay" },
      WAC: { zh: "灣仔", en: "Wan Chai" },
      ADM: { zh: "金鐘", en: "Admiralty" },
      CEN: { zh: "中環", en: "Central" },
      SHW: { zh: "上環", en: "Sheung Wan" },
      SYP: { zh: "西營盤", en: "Sai Ying Pun" },
      HKU: { zh: "香港大學", en: "HKU" },
      KET: { zh: "堅尼地城", en: "Kennedy Town" },
    },
  },
  KTL: {
    zh: "觀塘綫",
    en: "Kwun Tong Line",
    color: "#7ED321",
    up_terminus: "調景嶺",
    down_terminus: "黃埔",
    stations: {
      TIK: { zh: "調景嶺", en: "Tiu Keng Leng" },
      YAT: { zh: "油塘", en: "Yau Tong" },
      LAT: { zh: "藍田", en: "Lam Tin" },
      KWT: { zh: "觀塘", en: "Kwun Tong" },
      NTK: { zh: "牛頭角", en: "Ngau Tau Kok" },
      KOB: { zh: "九龍灣", en: "Kowloon Bay" },
      CHH: { zh: "彩虹", en: "Choi Hung" },
      DIH: { zh: "鑽石山", en: "Diamond Hill" },
      WTS: { zh: "黃大仙", en: "Wong Tai Sin" },
      LOF: { zh: "樂富", en: "Lok Fu" },
      KOT: { zh: "九龍塘", en: "Kowloon Tong" },
      SKM: { zh: "石硤尾", en: "Shek Kip Mei" },
      PRE: { zh: "太子", en: "Prince Edward" },
      MOK: { zh: "旺角", en: "Mong Kok" },
      YMT: { zh: "油麻地", en: "Yau Ma Tei" },
      HOM: { zh: "何文田", en: "Ho Man Tin" },
      WHA: { zh: "黃埔", en: "Whampoa" },
    },
  },
  LRT: {
    zh: "輕鐵",
    en: "Light Rail",
    color: "#C8102E",
    up_terminus: "屯門碼頭",
    down_terminus: "元朗",
    stations: {
      1: { zh: "屯門碼頭", en: "Tuen Mun Ferry Pier" },
      10: { zh: "美樂", en: "Melody Garden" },
      15: { zh: "蝴蝶", en: "Butterfly" },
      20: { zh: "輕鐵車廠", en: "Light Rail Depot" },
      30: { zh: "龍門", en: "Lung Mun" },
      40: { zh: "青山村", en: "Tsing Shan Tsuen" },
      50: { zh: "青雲", en: "Tsing Wan" },
      60: { zh: "建安", en: "Kin On" },
      70: { zh: "河田", en: "Ho Tin" },
      75: { zh: "蔡意橋", en: "Choy Yee Bridge" },
      80: { zh: "澤豐", en: "Chaak Fung" },
      90: { zh: "屯門醫院", en: "Tuen Mun Hospital" },
      100: { zh: "兆康", en: "Siu Hong" },
      110: { zh: "麒麟", en: "Kei Lun" },
      120: { zh: "青松", en: "Ching Chung" },
      130: { zh: "建生", en: "Kin Sang" },
      140: { zh: "田景", en: "Tin King" },
      150: { zh: "良景", en: "Leung King" },
      160: { zh: "新圍", en: "San Wai" },
      170: { zh: "石排", en: "Shek Pai" },
      180: { zh: "山景(北)", en: "Shan King (North)" },
      190: { zh: "山景(南)", en: "Shan King (South)" },
      200: { zh: "鳴琴", en: "Ming Kum" },
      212: { zh: "大興(北)", en: "Tai Hing (North)" },
      220: { zh: "大興(南)", en: "Tai Hing (South)" },
      230: { zh: "銀圍", en: "Ngan Wai" },
      240: { zh: "兆禧", en: "Siu Hei" },
      250: { zh: "屯門泳池", en: "Tuen Mun Swimming Pool" },
      260: { zh: "豐景園", en: "Fung King Garden" },
      265: { zh: "兆麟", en: "Siu Lun" },
      270: { zh: "安定", en: "On Ting" },
      275: { zh: "友愛", en: "Yau Oi" },
      280: { zh: "市中心", en: "Town Centre" },
      295: { zh: "屯門", en: "Tuen Mun" },
      300: { zh: "杯渡", en: "Pui To" },
      310: { zh: "何福堂", en: "Ho Fuk Tong" },
      320: { zh: "新墟", en: "San Hui" },
      330: { zh: "景峰", en: "King Fung" },
      340: { zh: "鳳地", en: "Fung Tei" },
      350: { zh: "藍地", en: "Lam Tei" },
      360: { zh: "泥圍", en: "Nai Wai" },
      370: { zh: "鍾屋村", en: "Chung Uk Tsuen" },
      380: { zh: "洪水橋", en: "Hung Shui Kiu" },
      390: { zh: "塘坊村", en: "Tong Fong Tsuen" },
      400: { zh: "屏山", en: "Ping Shan" },
      425: { zh: "坑尾村", en: "Hang Mei Tsuen" },
      430: { zh: "天水圍", en: "Tin Shui Wai" },
      435: { zh: "天榮", en: "Tin Wing" },
      445: { zh: "天富", en: "Tin Fu" },
      448: { zh: "頌富", en: "Chung Fu" },
      450: { zh: "天瑞", en: "Tin Shui" },
      455: { zh: "天湖", en: "Tin Wu" },
      460: { zh: "銀座", en: "Ginza" },
      468: { zh: "天慈", en: "Tin Tsz" },
      480: { zh: "濕地公園", en: "Wetland Park" },
      490: { zh: "天秀", en: "Tin Sau" },
      500: { zh: "天耀", en: "Tin Yiu" },
      510: { zh: "元朗", en: "Yuen Long" },
      520: { zh: "康樂路", en: "Hong Lok Road" },
      530: { zh: "大棠路", en: "Tai Tong Road" },
      540: { zh: "豐年路", en: "Fung Nin Road" },
      550: { zh: "水邊圍", en: "Shui Pin Wai" },
      560: { zh: "頌富", en: "Chung Fu" },
      570: { zh: "元朗公園", en: "Yuen Long Park" },
      580: { zh: "聚星樓", en: "Tsui Sing Lau" },
      590: { zh: "十八鄉", en: "Shap Pat Heung" },
      600: { zh: "橫洲", en: "Wang Chau" },
      610: { zh: "耀安", en: "Yiu On" },
    },
  },
};
